name: Generate

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      DPRINT_CACHE_DIR: /tmp/dprint-cache
    container:
      image: kula/golang-toolbox:trixie
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Cache dprint artifacts
        uses: actions/cache@v5
        with:
          path: ${{ env.DPRINT_CACHE_DIR }}
          key: dprint-${{ hashFiles('dprint.json') }}
          restore-keys: dprint-

      - name: Verify Generate
        run: |
          git config --global --add safe.directory "$(pwd)"
          make verify-generate
