name: Test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Run Tests
        run: make test

  e2e:
    name: Test E2E
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Install kind
        uses: helm/kind-action@v1
        with:
          install_only: true

      - name: Create kind cluster
        uses: azure/setup-helm@v5

      - name: Install swaks
        run: sudo apt-get update && sudo apt-get install -y swaks

      - name: Run E2E Tests
        run: make test-e2e

      - name: Teardown kind
        if: always()
        run: make kind-down
